databases:
  - name: weather-app-db
    databaseName: weather_app_production
    user: weather_app

services:
  - type: web
    name: weather-app
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: weather-app-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: ADDRESS_API_KEY
        sync: false
      - key: WEATHER_API_KEY
        sync: false
      - key: RAILS_ENV
        value: production
